- hosts: 172.17.0.5
  tasks:
    - maven_artifact:
        group_id: com.example
        artifact_id: demo
        version: 0.0.1
        repository_url: 'http://host.docker.internal:8110/repository/full-pipeline/'
        username: admin
        password: November@2021
        dest: /download
        
- hosts: 172.17.0.5
  tasks:
   - name: Update APT package manager repositories cache
     become: true
     yum:
      update_cache: yes
   - name: Install Java using Ansible
     become: yes
     yum:
      name: "{{packages}}"
      state: present
     vars:
      packages:
         - java-1.8.0-openjdk.x86_64
         
- hosts: 172.17.0.5
  vars:
    app_name: demo-latest

  tasks:
   - name: create service file
     template:
       src: example.j2
       dest: /etc/systemd/system/demo-latest.service

   - name: start service
     service:
        name: demo-latest.service
        state: restarted
